### ISSUE TITLE
Improve PHP 8.1.0 support...

### ISSUE THREAD

**Issue by lotestudio** [spatie/period#106]
There is a warning if use strings for dates:
<pre>
$period = Period::make('2021-01-01', '2021-01-31');

PHP Deprecated:  str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in ****/vendor/spatie/period/src/PeriodFactory.php on line 122
</pre>

**Comment by brendt** [comment]
Fixed in 2.3.3: https://github.com/spatie/period/releases/tag/2.3.3
