### ISSUE TITLE
Returns PeriodCollection with null element

### ISSUE THREAD

**Issue by Lednick** [spatie/period#14]
When I try to use PeriodCollection's function isEmpty this return false, but when i dump 

<img width="352" alt="screen shot 2019-01-08 at 12 20 40 pm" src="https://user-images.githubusercontent.com/22300409/50824905-68499c00-1340-11e9-838a-a1b48dbd9c92.png">
 
I have that:

<img width="245" alt="screen shot 2019-01-08 at 12 20 32 pm" src="https://user-images.githubusercontent.com/22300409/50824866-57008f80-1340-11e9-9741-c64a8f92ae49.png">

So method isEmpty works not right, because array only with one null element.

Here in my code:
<img width="787" alt="screen shot 2019-01-08 at 12 25 25 pm" src="https://user-images.githubusercontent.com/22300409/50824951-81eae380-1340-11e9-99aa-16393848cb48.png">

Can you fix this issue?

**Comment by brendt** [comment]
Can you specify the concrete values of `$dateFrom`, `$dateTo`, `$compareDateFrom` and `$compareDateto` ?

**Comment by Lednick** [comment]
$dateFrom = 2019-01-08 12:32:49.0 UTC (+00:00)

**Comment by brendt** [comment]
Fixed in 0.4.1: https://github.com/spatie/period/releases/tag/0.4.1
