### ISSUE TITLE
PeriodCollection with null element after diff

### ISSUE THREAD

**Issue by alnidok** [spatie/period#23]
Hi, if I calculate diff between two not intersected periods and try to loop:
**Return value of Spatie\Period\PeriodCollection::current() must be an instance of Spatie\Period\Period, null returned**

```php
$dayPeriod = Period::make('2019-02-01 15:00:00', '2019-02-01 20:00:00', Precision::MINUTE);
$events = new PeriodCollection(
    // $dayPeriod does not contain this event
    Period::make('2019-02-01 10:00:00', '2019-02-01 14:00:00', Precision::MINUTE)
);
$periods = $dayPeriod->diff(...$events);

foreach ($periods as $period) { //throw TypeError
    var_dump($period);
}
```

**Comment by brendt** [comment]
Thanks for reporting this bug! It's fixed in 1.1.1: https://github.com/spatie/period/releases/tag/1.1.1
