### ISSUE TITLE
Overlap all (n^2)

### ISSUE THREAD

**Issue by t0xxie** [spatie/period#27]
```
/*
 * A       [========]
 * B             [==]
 * C                                         [=====]
 * D                                         [===============]
 *
 * OVERLAP       [==]                        [=====]
 */
```

how would one combine the given overlap,diff,and gap functions to get 
such collection as described in the graph above?

**Comment by brendt** [comment]
Seems like an `overlapAny` function would be useful? I'd accepted a tested PR for that.

**Comment by brendt** [comment]
To answer your question on the top of my head: I'd first loop over all periods and group them together whether they overlap or not, and than calculate the overlaps for each group.

**Comment by t0xxie** [comment]
could u make software that produces php code for any input graph ?

**Comment by brendt** [comment]
I'm not sure what you mean. I'll be closing this issue and await for a PR to appear.
