### ISSUE TITLE
[2.0] Period::overlap methods

### ISSUE THREAD

**Issue by brendt** [spatie/period#30]
`Period` has three ways of overlapping:

```php
Period::overlapSingle(Period $period): ?Period
Period::overlap(Period ...$periods): PeriodCollection
Period::overlapAll(Period ...$periods): ?Period
```

The naming here is very confusing, and I'd like this to improved with v2.

**Period::overlapSingle** will determine the overlap between two periods, and return a single `Period` or `null`.

```php
A        [===========]
B            [============]

OVERLAP      [=======]
```

The more obvious name would simply be `overlap`.

**Period::overlap** allows for overlapping multiple periods on each other:

```php
A       [========]
B                   [==]
C                           [=====]
D              [===============]

OVERLAP        [=]   [==]   [==]
```

This name is confusing, I can think of two improvements:

- `Period::overlapAny(Period ...$periods)`
- `PeriodCollection::overlapAny()`

They would have a subtle difference: `Period::overlapAny(Period ...$periods)` would compare each period to the "master period", while `PeriodCollection::overlapAny()` would compare all periods in the collection to each other.

**Period::overlapAll** is also confusing, it does the following:

```php
A              [============]
B                   [==]
C                   [=======]

OVERLAP             [==]
```

I believe the correct solution would be to move this functionality to `PeriodCollection::overlapAll()` — although I think we should come up with a better name.

Again we could keep the shorthand on `Period`.

Another issue with `Period::overlapAll` is that it can only return one period, while this could also be possible with collection

```php
COLLECTION A              [===============================]
COLLECTION B                   [==]             [=======]
COLLECTION C                   [=======]      [======]

COLLECTION OVERLAP             [==]             [====]
```

**Comment by brendt** [comment]
@jeromegamez I'd like your input on this.

**Comment by jeromegamez** [comment]
I'm struggling with writing down what I would suggest to do - would you be okay with a PR in which I _just do it™_ and document my reasoning there?

**Comment by brendt** [comment]
Sure thing! I'm tinkering myself with it, but I'm happy with all input I can get

**Comment by jeromegamez** [comment]
My head is 🤯😅

**Comment by jeromegamez** [comment]
Okay, after getting carried away while coding (as usual), here's what I would probably pursue:

The presumption is that `get*` always returns an expected type and `find*` returns an expected type or `null`

- Change `Period::overlapSingle()` to `Period::findOverlapIn()`
  - Sidenote: `Period::overlapsWith()` could return `(bool) Period::findOverlapIn();`

- Change `Period::overlap(Period ...$periods)` to `Period::getOverlapsWithPeriodsIn(PeriodCollection $collection)`
  - A new convenience method `Period::overlapsWithPeriodsIn($collection)` could return `!$this->getOverlapsIn($collection)->isEmpty();`

- Remove `Period::overlapAll()`
  - It seems to me that `overlapAll()` is the same as `overlap()`/`getOverlapsWithPeriodsIn()`
  - Even if it's not, the issue you described (currently returns `Period`, but the correct result could also be a collection.

So, my target class would be

```php
class Period
{
    // ...

    public function findOverlapIn(Period $other): ?Period
    {
         // ..
    }

    public function overlapsWith(Period $other): bool
    {
        return (bool) $this->findOverlapIn($other);
    }

    public function getOverlapsWithPeriodsIn(PeriodCollection $collection): PeriodCollection
    {
        // ...
    }

    public function overlapsWithPeriodsIn(PeriodCollection $collection): bool
    {
        return !$this->getOverlapsWithPeriodsIn($collection)->isEmpty();
    }

    // ...
}
```

The developer can then work with the returned collection

In general, I would change everything except constructors to accept `PeriodCollection`s only - we have this type, so people should use it - chances are that if someone works with multiple Periods, they also create PeriodCollections somewhere during the process. This could avoid the question "where do I use PeriodCollections, where to I use an array of Periods, where do I use a list of Periods?"

**Comment by brendt** [comment]
Thanks for the input Jérôme! I'm not sure if we should go this route though. Adding `find` and `get` introduces extra verbosity. I'm struggling to decide whether the clarity outweighs the verbosity.

While I do agree on using more `PeriodCollections`, I also think that this could add extra overhead. But what if we allowed all kinds of input: `...$periods`, and cast them to a `PeriodCollection`. This means the user could provide several periods, an array of periods or a `PeriodCollection`, whatever they like the most.

Regarding the names: I'll rebase my local branch once #32 has been merged, so that you can take a look at my proposal.
