### ISSUE TITLE
Get all overlapsed dates from collection

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [spatie/period#63]
Hello,
I need to get a range of overlapping dates from a collection.

Maybe I missed something in the docs but I can not find something like: 
```
$collection = new PeriodCollection(
    Period::make('2018-01-01', '2018-01-05'),
    Period::make('2018-01-10', '2018-01-15'),
    Period::make('2018-01-20', '2018-01-25'),
    Period::make('2018-01-30', '2018-01-31')
);

$gaps = $collection->gaps();
```

But getting: 
`$overlaps = $collection->overlaps();`
instead of gaps

Would that be possible ?

Best regards

**Comment by ShapesGraphicStudio** [comment]
Hi again,

I do not know if it's the best way to get there, but in case it can help somebody spare some time, here's what I did: 

```
$periods = [];

foreach($items as $item) {
    if($item->model->time_limited) {
        $periods[$item->id] = Period::make($item->available_from,$item->available_to);
    }
}

$collection = new PeriodCollection(...$periods);
$boundaries = $collection->boundaries();

$overlaps = $boundaries->overlapAll(...$periods);
```

Seems to work fine.
Best regards

**Comment by brendt** [comment]
My thought would be as you did, getting the boundaries of the collection and overlapping each individual period to that. Feel free to submit a PR to add eg. `overlapAny` to the `PeriodCollection` class.
