### ISSUE TITLE
Scheduling "things"

### ISSUE THREAD

**Issue by tarekadam** [spatie/period#64]
I'm using https://github.com/spatie/period for complex calendar operations.  It's great, but it would be better if I could attach "things".  For example, schedule a "vacation" and then be able to retrieve that vacation or vacations from Period or PeriodCollection.  That way I would see which of my vacations are overlapping.  I realize the inverse is possible: my vacation hasa Period.  However that doesn't flow forward into the PeriodCollection of Overlaps... Which vacations are overlapping?

**Comment by brendt** [comment]
I think that's outside the scope of this package, you could build a kind of "timeline" feature using this package underneath, but I guess you're already doing that. You're also free to extend `PeriodCollection` and do whatever you like with it.
