### ISSUE TITLE
touchesWith() does not take precision into consideration

### ISSUE THREAD

**Issue by tania-pets** [spatie/period#67]
Seems that `touchesWith()` will always return true if the compared periods are in the same day, even if the times are not really touched and the precision is SECOND.

Example:

```
$a = Period::make('2018-01-01 06:30:00', '2018-01-01 07:30:00');
$b = Period::make('2018-01-01 09:00:00', '2018-01-01 10:00:00');
$overlap = $a->touchesWith($b);
(true)
```

This leads to `gap()` function not detecting the [gap](https://github.com/spatie/period/blob/master/src/Period.php#L283) for such cases.

**Comment by freekmurze** [comment]
We accept a PR that adds a test and a fix for this.

**Comment by kukko** [comment]
I'll be happy to try to solve this issue.

**Comment by freekmurze** [comment]
Warning: the principal author of the package thinks that this is a difficult change: https://twitter.com/brendt_gd/status/1313127606640881671

**Comment by kukko** [comment]
I also created a pull request which not add precision parameter, but it is calculate the difference between the dates correctly. #69

**Comment by brendt** [comment]
Fixed with https://github.com/spatie/period/releases/tag/1.5.1
