### ISSUE TITLE
Carry over exclusion

### ISSUE THREAD

**Issue by ameenross** [spatie/period#75]
At first I thought this was an off by one error, but it's not quite. It's just a nasty gotcha because the boundary exclusions are not carried over. Here's code with the problem.

```php
// Period for entire month of January.
$january = new Period(
    new DateTimeImmutable('2021-01-01'),
    new DateTimeImmutable('2021-02-01'),
    Precision::SECOND,
    Boundaries::EXCLUDE_END
);

// Remove something.
$firstPartOfJanuary = $january->diff(new Period(
    new DateTimeImmutable('2021-01-22'),
    new DateTimeImmutable('2021-02-01'),
    Precision::SECOND,
    Boundaries::EXCLUDE_END
))[0];

// Now I'm expecting end to be 2021-01-22 0:00. It isn't:
$firstPartOfJanuary->getEnd()->format('c'); // 2021-01-21T23:59:59+01:00

// That is because:
$firstPartOfJanuary->endExcluded(); // false
```

I'm expecting the end to be excluded, as both input periods have EXCLUDE_END...

**Comment by brendt** [comment]
Ah yes, good catch; thanks for reporting! Do you want to submit a bugfix yourself? Otherwise I'll look at this somewhere next week.

**Comment by ameenross** [comment]
I don't think I will be able to soon. However, thinking about this again, I think the way the boundaries are programmed means resulting periods should have boundary inclusion/exclusion depending on more factors. Basically, a period has 2 boundaries, and if one of a boundary is not included, it needs to be included in the period before or after that. So say We have this:

```
// ----------[     )------
// -----------------(----]
```

Then there is really a "gap" between these periods in the form of a single moment in time. Or in other words, they *nearly* touch.
So if you want to get the gap between two periods, here's what should happen

```
// A:   ----------[     )------
// B:   -------------------[--)
// GAP: ----------------[--)---
```

**Comment by brendt** [comment]
We'll continue this conversation in #80, it'll be fixed in v2.
