### ISSUE TITLE
Add a Period->coversDate method

### ISSUE THREAD

**Issue by IwfY** [spatie/period#8]
I have use cases for this library but what prevents me from using it is a convenient **Period->coversDate** method that receives a DateTime object and two mode information for whether the start/end of the period are included or excluded. The mode may also be be combined to a single parameter.

Would this be possible and within the scope of this library?

**Comment by brendt** [comment]
@IwfY definitely! Are you up for sending a PR with tests?

**Comment by IwfY** [comment]
@brendt Unfortunately not at the moment. I'm sorry.

**Comment by brendt** [comment]
No problem, I'll add it.

Just to be clear about the mode thing: you want to be able to include or exclude the start and end date of the period, right? Can you give an example of when you'd want to exclude the boundaries?

**Comment by IwfY** [comment]
I work with the convention to always include the start and exclude the end. But I thought it was more in line with the existing methods like **startAfter** and **startAfterOrAt**.

**Comment by brendt** [comment]
Are there any known benefits to excluding the end date?

**Comment by IwfY** [comment]
I need time sensible periods. I know that this package is/was primary based on days. That is why the scope is important to decide.

The advantage for me is that when I'm working with sequential periods I can set the start of the second period and the end of the first to the same moment in time and don't have to subtract an arbitrary fraction of seconds from this moment to have a non-overlapping end for the first period.

**Comment by brendt** [comment]
I see you're point 🤔

I find it difficult to decide what's better. On the one hand excluding the end date is convenient, but it also adds some cognitive load. The developer has to keep in mind this unwritten rule.

I'm going to open a separate issue to further discuss this. For now `Period::contains` has been added and tagged as 0.3.0: https://github.com/spatie/period/releases/tag/0.3.0

**Comment by brendt** [comment]
For reference, we'll discuss the boundaries more in depth in this issue: https://github.com/spatie/period/issues/9

**Comment by IwfY** [comment]
@brendt I think something went wrong with this commit!? I don't see the contains method in this repo.
