### ISSUE TITLE
Precision - Overlap by X minutes

### ISSUE THREAD

**Issue by lsv** [spatie/period#83]
Would a overlap by X minutes be a good idea?

So this

`2020-01-01 15:15:00` would overlap `2020-01-01 15:00:00`

if `Precision::MINUTE(15)` was set, great for calendars I think.

**Comment by brendt** [comment]
That's an interesting idea! We could say the same for all kinds of precisions, not just minutes. I'll think about how we can implement this!

**Comment by akalongman** [comment]
Also interested in this feature
