### ISSUE TITLE
Visualization bugs

### ISSUE THREAD

**Issue by tsterker** [spatie/period#86]
---

> ℹ️ _Apologies for the brief "issue dump", but my time is currently limited and I wanted to report this already._
> _Maybe I'll find time to provide details and/or PRs._
>
> _Also, thanks for this great package!_

---

I found some bugs in the visualizer. My setup is the following:

```php
use Spatie\Period\Visualizer;
use Spatie\Period\Period;

$v = new Visualizer(['width' => 10]);

$periods = [ /* ... */ ];

echo "\n" . $v->visualize($periods) . "\n";
```

## 1. Visualization of less than 2 periods

> ⚠️ max(): When only one parameter is given, it must be an array

```php
// CASE: No periods
$periods = [];

// CASE: Only one period
$periods = [
  Period::make(now(), now()->addDay())
];
```

## 2. Visualization of period spanning no more than one day

> ⚠️ Division by zero

```php
$periods = [
  Period::make(now(), now()),
  Period::make(now(), now())
];
```

### Single-day periods not renderd
```php
$periods = [
     \Spatie\Period\Period::make(now(), now()),
     \Spatie\Period\Period::make(now(), now()->addDay()),
     \Spatie\Period\Period::make(now(), now()),
];
```

> ```
> 0              
> 1    [========]
> 2  
> ```

### Single-day periods rendered depending on the width
Varying the visualization `width` seems to affect the outcome.

Assume the following periods:

```php
$periods = [
    Period::make(now(), now()),
    Period::make(now()->addDay(), now()->addDay()),
    Period::make(now()->subDays(38), now()->addDays(2)),
];
```

**Width: 50** (all periods rendered)
```php
$v = new Visualizer(['width' => 50]);
```

> ```
> 0                                                   =  
> 1                                                    = 
> 2    [================================================]
> ```

**Width: 60** (one period "gone")
```php
$v = new Visualizer(['width' => 60]);
```

> ```
> 0                                                                
> 1                                                              = 
> 2    [==========================================================]
> ```

**Comment by brendt** [comment]
Feel free to submit a PR when you've got the time, I don't think I'll be looking into this anytime soon myself.
